"""new fields in user model

Revision ID: 38874e066345
Revises: 4a20039d5d91
Create Date: 2025-03-10 11:29:18.928477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38874e066345'
down_revision = '4a20039d5d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
